heat_template_version: 2015-04-30
description: Template for creating a network


parameters:

  floating_pool:
    type: string
    label: Floating pool name (for instance floating ip)
    default: "int-net"
    constraints:
      - custom_constraint: neutron.network

  subnet_pool:
    type: string
    label: "The ID of the subnetpool to use"
    default: "tenant-subnetpool4"

  nameservers:
    type: comma_delimited_list
    label: Nameservers for the k8s subnet
    default: 195.74.0.47,195.197.54.100

  keypair_name:
    type: string
    label: Keypair name

  public_key:
    type: string
    label: public key


resources:

  network:
    type: OS::Neutron::Net
    properties:
      name: {
        list_join: [
          '-',
          [{ get_param: 'OS::stack_name' }, 'net']
        ]
      }

  subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network }
      subnetpool: { get_param: subnet_pool }
      dns_nameservers: { get_param: nameservers }
      name: {
        list_join: [
          '-',
          [{ get_param: 'OS::stack_name' }, 'subnet']
        ]
      }

  router:
    type: OS::Neutron::Router
    properties:
      name: {
        list_join: [
          '-',
          [{ get_param: 'OS::stack_name' }, 'router']
        ]
      }
      external_gateway_info:
        network: { get_param: floating_pool }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: subnet }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: {
        list_join: [
          '-',
          [{ get_param: 'OS::stack_name' }, 'sg']
        ]
      }
      rules: [
        {protocol: udp,
        remote_mode: remote_group_id,
        port_range_min: 1,
        port_range_max: 65535},
        {protocol: tcp,
        remote_mode: remote_group_id,
        port_range_min: 1,
        port_range_max: 65535},
        {protocol: tcp,
        remote_ip_prefix: "0.0.0.0/0",
        port_range_min: 22,
        port_range_max: 22}]

  keypair:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: keypair_name }
      public_key: { get_param: public_key }


outputs:

  network_id:
    description: network id
    value: { get_resource: network }

  subnet_id:
    description: subnet id
    value: { get_resource: subnet }

  security_group_id:
    description: security group id
    value: { get_resource: security_group }

  keypair_name:
    description: key pair name
    value: { get_param: keypair_name }

